---
- hosts: all
  vars:
    spark_home: /opt/spark
    spark_pkg_name: spark-3.3.1-bin-hadoop3
    spark_pkg_url: https://downloads.apache.org/spark/spark-3.3.1/spark-3.3.1-bin-hadoop3.tgz

  tasks:
    - name: Update all packages to the latest version
      become: true
      apt:
        upgrade: dist
        update_cache: yes

    - name: Basic dependencies
      become: true
      apt:
        name: ['software-properties-common', 'python3-software-properties', 'curl', 'git', 'vim']
        state: latest
        update_cache: yes
        force_apt_get: true

    - name: Install AdoptOpenJDK 11
      become: true
      block:
        - name: Import keys
          apt_key:
            url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
            state: present
        - name: Add repository
          apt_repository:
            repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial main
            state: present
        - name: Install package
          apt:
            name: ['adoptopenjdk-11-hotspot', 'ca-certificates']
            state: latest
            update_cache: yes
            force_apt_get: true

    - name: Clone classrom repository
      git:
        repo: 'https://github.com/luisbelloch/data_processing_course.git'
        dest: '{{ ansible_env.HOME }}/data_processing_course'

    - stat:
        path: '/opt/{{ spark_pkg_name }}'
      register: spark_dest

    - name: Install SPARK
      when: spark_dest.stat.islnk is not defined
      block:
        - name: Download Spark
          become: true
          unarchive:
            src: '{{ spark_pkg_url }}'
            dest: /opt
            remote_src: yes

        - name: Link to latest version
          become: true
          file:
            state: link
            src: '/opt/{{ spark_pkg_name }}'
            dest: '{{ spark_home }}'

        - name: Add Spark to PATH
          lineinfile:
            path: '{{ ansible_env.HOME }}/.bashrc'
            line: 'export PATH=$PATH:/opt/{{ spark_pkg_name }}/bin'

        - name: Set PySpark Python version to 3
          lineinfile:
            path: '{{ ansible_env.HOME }}/.bashrc'
            line: 'export PYSPARK_PYTHON=python3'

        # https://bugs.python.org/issue19846
        - name: Update locale
          become: true
          command: update-locale LC_ALL=en_US.UTF-8

